import {
  IconBrandAdobeIllustrator,
  IconBrandAdobePhotoshop,
  IconBrandAdonisJs,
  IconBrandAlgolia,
  IconBrandAlpineJs,
  IconBrandAngular,
  IconBrandAstro,
  IconBrandAws,
  IconBrandBootstrap,
  IconBrandBulma,
  IconBrandCss3,
  IconBrandDeno,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandEnvato,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandFlutter,
  IconBrandFramer,
  IconBrandFramerMotion,
  IconBrandGatsby,
  IconBrandGraphql,
  IconBrandHtml5,
  IconBrandJavascript,
  IconBrandKotlin,
  IconBrandLaravel,
  IconBrandMongodb,
  IconBrandMysql,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandNuxt,
  IconBrandPhp,
  IconBrandPnpm,
  IconBrandReact,
  IconBrandReactNative,
  IconBrandRedux,
  IconBrandRust,
  IconBrandSass,
  IconBrandSvelte,
  IconBrandSymfony,
  IconBrandTailwind,
  IconBrandTypescript,
  IconBrandVercel,
  IconBrandVue,
  IconBrandWebflow,
  IconBrandWix,
  IconBrandWordpress,
  IconBrandYarn,
} from '@tabler/icons-react';

export const iconConfigs = [
  { Icon: IconBrandHtml5, color: '#e34f26' },
  { Icon: IconBrandCss3, color: '#002561' },
  { Icon: IconBrandSass, color: '#c13584' },
  { Icon: IconBrandReact, color: '#00d8ff' },
  { Icon: IconBrandReactNative, color: '#4d4f53' },
  { Icon: IconBrandNodejs, color: '#44883e' },
  { Icon: IconBrandAdonisJs, color: '#774aa4' },
  { Icon: IconBrandNextjs, color: '#26313b' },
  { Icon: IconBrandAngular, color: '#b52e31' },
  { Icon: IconBrandAlpineJs, color: '#0cb9c1' },
  { Icon: IconBrandAlgolia, color: '#037ef3' },
  { Icon: IconBrandPhp, color: '#4f5b93' },
  { Icon: IconBrandRedux, color: '#854c9e' },
  { Icon: IconBrandVercel, color: '#3b4446' },
  { Icon: IconBrandDocker, color: '#0db7ed' },
  { Icon: IconBrandJavascript, color: '#f7df1e' },
  { Icon: IconBrandTypescript, color: '#3178c6' },
  { Icon: IconBrandNpm, color: '#cb3837' },
  { Icon: IconBrandYarn, color: '#006e96' },
  { Icon: IconBrandPnpm, color: '#d79100' },
  { Icon: IconBrandTailwind, color: '#439fd3' },
  { Icon: IconBrandBootstrap, color: '#774aa4' },
  { Icon: IconBrandBulma, color: '#00b7c9' },
  { Icon: IconBrandFramerMotion, color: '#cd595a' },
  { Icon: IconBrandFramer, color: '#eeb111' },
  { Icon: IconBrandAdobePhotoshop, color: '#00386b' },
  { Icon: IconBrandGraphql, color: '#e1306c' },
  { Icon: IconBrandMongodb, color: '#60ab59' },
  { Icon: IconBrandMysql, color: '#1e8cbe' },
  { Icon: IconBrandAdobeIllustrator, color: '#fcaf45' },
  { Icon: IconBrandFigma, color: '#FF3737' },
  { Icon: IconBrandEnvato, color: '#00b22d' },
  { Icon: IconBrandFirebase, color: '#ff9500' },
  { Icon: IconBrandFlutter, color: '#6caddf' },
  { Icon: IconBrandWordpress, color: '#21759b' },
  { Icon: IconBrandWebflow, color: '#333333' },
  { Icon: IconBrandWix, color: '#1e1e1e' },
  { Icon: IconBrandAstro, color: '#0cf' },
  { Icon: IconBrandDjango, color: '#092e20' },
  { Icon: IconBrandGatsby, color: '#663399' },
  { Icon: IconBrandKotlin, color: '#0095d5' },
  { Icon: IconBrandLaravel, color: '#ff2d20' },
  { Icon: IconBrandRust, color: '#dea584' },
  { Icon: IconBrandSvelte, color: '#ff3e00' },
  { Icon: IconBrandSymfony, color: '#000000' },
  { Icon: IconBrandVue, color: '#4fc08d' },
  { Icon: IconBrandNuxt, color: '#00c58e' },
  { Icon: IconBrandDeno, color: '#000000' },
  { Icon: IconBrandAws, color: '#ff9900' },
];
