import { TooltipProvider } from '@/components/ui/tooltip';
import type { Metadata } from 'next';
import { IBM_Plex_Mono, Lato, Nunito } from 'next/font/google';

import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--display-family',
});
const nunito = Nunito({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--body-family',
});
const ibm_plex_mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${lato.variable} ${nunito.variable} ${ibm_plex_mono.variable}`}>
      <body className={`font-body antialiased`}>
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
